"""Build-time provider contract stamp. Generated by CMake — do not edit.

See cmake/python-wheel-install.cmake for how each value is derived.
"""

#: Native library version (TRANSCRIBE_VERSION_* macros in include/transcribe.h).
VERSION = "0.2.3"

#: Public-header digest the committed FFI layer (_generated.py) was generated
#: from. The binding refuses to load a provider built against a different ABI.
PUBLIC_HEADER_HASH = "7df72bf9e667b8c2"

#: Backend kinds compiled into this artifact (modules may still degrade to
#: unavailable at runtime, e.g. Vulkan without a loader/driver).
BACKENDS = ("vulkan", "cpu",)
