#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use cpal::traits::{DeviceTrait, HostTrait, StreamTrait};
use libloading::Library;
use std::ffi::{c_char, c_void, CStr, CString};
use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};
use std::path::PathBuf;
use std::sync::{mpsc, Arc, Mutex};
use std::thread;

#[link(name = "kernel32")]
extern "system" { fn SetDllDirectoryW(path: *const u16) -> i32; }

type Status = i32;
const OK: Status = 0;
const BACKEND_VULKAN: i32 = 3;
const EXT_PARAKEET_STREAM: u32 = 0x54534B50;

#[repr(C)] struct ModelLoad { size: u64, backend: i32, _pad: i32, device: *mut c_void }
#[repr(C)] struct SessionParams { size: u64, threads: i32, kv: i32, ctx: i32 }
#[repr(C)] struct Ext { size: u64, kind: u32, _pad: u32 }
#[repr(C)] struct ParakeetExt { ext: Ext, right: i32, _pad: i32 }
#[repr(C)] struct RunParams { size: u64, task: i32, timestamps: i32, pnc: i32, itn: i32, diarize: i32, language: *const c_char, target: *const c_char, keep: bool, _pad: [u8; 7], family: *const Ext, spec: i32, _tail: [u8; 4] }
#[repr(C)] struct StreamParams { size: u64, family: *const Ext, policy: i32, stable: u32 }
#[repr(C)] struct Update { size: u64, changed: bool, final_: bool, revision: i32, received: i64, committed: i64, buffered: i64, committed_changed: bool, tentative_changed: bool, _pad: [u8; 5] }
#[repr(C)] struct Text { size: u64, full: *const c_char, full_n: u64, committed: *const c_char, committed_n: u64, tentative: *const c_char, tentative_n: u64, raw_start: u64 }

type Model = c_void; type Session = c_void;
struct Api { _lib: Library, load_backends: unsafe extern "C" fn() -> Status, load: unsafe extern "C" fn(*const c_char, *const ModelLoad, *mut *mut Model) -> Status, model_free: unsafe extern "C" fn(*mut Model), session_init: unsafe extern "C" fn(*mut Model, *const SessionParams, *mut *mut Session) -> Status, session_free: unsafe extern "C" fn(*mut Session), model_params_init: unsafe extern "C" fn(*mut ModelLoad), session_params_init: unsafe extern "C" fn(*mut SessionParams), run_params_init: unsafe extern "C" fn(*mut RunParams), stream_params_init: unsafe extern "C" fn(*mut StreamParams), parakeet_init: unsafe extern "C" fn(*mut ParakeetExt), stream_begin: unsafe extern "C" fn(*mut Session, *const RunParams, *const StreamParams) -> Status, feed: unsafe extern "C" fn(*mut Session, *const f32, i32, *mut Update) -> Status, finalize: unsafe extern "C" fn(*mut Session, *mut Update) -> Status, get_text: unsafe extern "C" fn(*const Session, *mut Text) -> Status, text_init: unsafe extern "C" fn(*mut Text), update_init: unsafe extern "C" fn(*mut Update), backend: unsafe extern "C" fn(*const Model) -> *const c_char }

impl Api { unsafe fn new(path: &PathBuf) -> Result<Self, String> { if let Some(dir)=path.parent() { let mut wide:Vec<u16>=dir.to_string_lossy().encode_utf16().chain(std::iter::once(0)).collect(); SetDllDirectoryW(wide.as_mut_ptr()); } let lib=Library::new(path).map_err(|e|e.to_string())?; macro_rules! s { ($n:literal,$t:ty)=>{*lib.get::<$t>($n).map_err(|e|e.to_string())?}; } Ok(Self{load_backends:s!(b"transcribe_init_backends_default\0",unsafe extern "C" fn()->Status),load:s!(b"transcribe_model_load_file\0",unsafe extern "C" fn(*const c_char,*const ModelLoad,*mut *mut Model)->Status),model_free:s!(b"transcribe_model_free\0",unsafe extern "C" fn(*mut Model)),session_init:s!(b"transcribe_session_init\0",unsafe extern "C" fn(*mut Model,*const SessionParams,*mut *mut Session)->Status),session_free:s!(b"transcribe_session_free\0",unsafe extern "C" fn(*mut Session)),model_params_init:s!(b"transcribe_model_load_params_init\0",unsafe extern "C" fn(*mut ModelLoad)),session_params_init:s!(b"transcribe_session_params_init\0",unsafe extern "C" fn(*mut SessionParams)),run_params_init:s!(b"transcribe_run_params_init\0",unsafe extern "C" fn(*mut RunParams)),stream_params_init:s!(b"transcribe_stream_params_init\0",unsafe extern "C" fn(*mut StreamParams)),parakeet_init:s!(b"transcribe_parakeet_stream_ext_init\0",unsafe extern "C" fn(*mut ParakeetExt)),stream_begin:s!(b"transcribe_stream_begin\0",unsafe extern "C" fn(*mut Session,*const RunParams,*const StreamParams)->Status),feed:s!(b"transcribe_stream_feed\0",unsafe extern "C" fn(*mut Session,*const f32,i32,*mut Update)->Status),finalize:s!(b"transcribe_stream_finalize\0",unsafe extern "C" fn(*mut Session,*mut Update)->Status),get_text:s!(b"transcribe_stream_get_text\0",unsafe extern "C" fn(*const Session,*mut Text)->Status),text_init:s!(b"transcribe_stream_text_init\0",unsafe extern "C" fn(*mut Text)),update_init:s!(b"transcribe_stream_update_init\0",unsafe extern "C" fn(*mut Update)),backend:s!(b"transcribe_model_backend\0",unsafe extern "C" fn(*const Model)->*const c_char),_lib:lib}) } }

#[derive(Default)] struct Shared { loaded: bool, recording: bool, processing: bool, text: String, error: String }
enum Cmd { Start(mpsc::Sender<Result<(),String>>), Stop(mpsc::Sender<Result<String,String>>), Shutdown }

fn set_error(shared:&Arc<Mutex<Shared>>, e:String) { let mut s=shared.lock().unwrap(); s.error=e; s.recording=false; s.processing=false; }
fn status_json(shared:&Arc<Mutex<Shared>>) -> String { let s=shared.lock().unwrap(); format!(r#"{{"loaded":{},"recording":{},"processing":{},"text":{},"error":{}}}"#,s.loaded,s.recording,s.processing,json_escape(&s.text),json_escape(&s.error)) }
fn json_escape(s:&str)->String { format!("\"{}\"",s.replace('\\',"\\\\").replace('"',"\\\"").replace('\n',"\\n").replace('\r',"\\r")) }
fn model_text(api:&Api, session:*mut Session)->String { unsafe { let mut t=Text{size:0,full:std::ptr::null(),full_n:0,committed:std::ptr::null(),committed_n:0,tentative:std::ptr::null(),tentative_n:0,raw_start:0}; (api.text_init)(&mut t); if (api.get_text)(session,&mut t)!=OK {return String::new()}; if t.full.is_null(){String::new()}else{CStr::from_ptr(t.full).to_string_lossy().into_owned()} } }
fn open_audio_stream(tx:mpsc::Sender<Vec<f32>>) -> Result<cpal::Stream,String> { let host=cpal::default_host(); let dev=host.default_input_device().ok_or("No hay micrófono")?; let cfg=dev.default_input_config().map_err(|e|e.to_string())?; let src=cfg.sample_rate().0 as f32; let channels=cfg.channels() as usize; let config=cfg.config(); let mut carry=Vec::<f32>::new(); let err=|e| eprintln!("audio: {e}"); let stream=match cfg.sample_format(){ cpal::SampleFormat::F32=>dev.build_input_stream(&config,move|d:&[f32],_|{ for frame in d.chunks(channels){carry.push(frame[0]);} let step=src/16000.0; let n=(carry.len() as f32/step).floor() as usize; if n>0 { let mut out=Vec::with_capacity(n); for i in 0..n { let p=i as f32*step; let a=p.floor() as usize; let f=p-a as f32; out.push(carry.get(a).copied().unwrap_or(0.0)*(1.0-f)+carry.get(a+1).copied().unwrap_or(0.0)*f); } let used=(n as f32*step).floor() as usize; carry.drain(..used.min(carry.len())); let _=tx.send(out); } },err,None), _=>return Err("El micrófono no entrega float32".into())}.map_err(|e|e.to_string())?; stream.play().map_err(|e|e.to_string())?; Ok(stream) }

unsafe fn begin_existing(api:&Api, session:*mut Session, shared:&Arc<Mutex<Shared>>, audio_rx:&mut Option<mpsc::Receiver<Vec<f32>>>, audio_stream:&mut Option<cpal::Stream>, reply:mpsc::Sender<Result<(),String>>) -> bool {
    let mut rp=RunParams{size:0,task:0,timestamps:0,pnc:0,itn:0,diarize:0,language:std::ptr::null(),target:std::ptr::null(),keep:false,_pad:[0;7],family:std::ptr::null(),spec:-1,_tail:[0;4]};
    (api.run_params_init)(&mut rp); let lang=CString::new("es-ES").unwrap(); rp.language=lang.as_ptr();
    let mut pe=ParakeetExt{ext:Ext{size:0,kind:0,_pad:0},right:3,_pad:0}; (api.parakeet_init)(&mut pe); pe.right=3;
    let mut stp=StreamParams{size:0,family:std::ptr::null(),policy:0,stable:0}; (api.stream_params_init)(&mut stp); stp.family=&pe.ext;
    if (api.stream_begin)(session,&rp,&stp)!=OK { set_error(shared,"No se pudo reiniciar el stream".into()); let _=reply.send(Err("No se pudo reiniciar el stream".into())); return false; }
    let (atx,arx)=mpsc::channel(); *audio_rx=Some(arx); *audio_stream=match open_audio_stream(atx){Ok(v)=>Some(v),Err(e)=>{set_error(shared,e.clone());let _=reply.send(Err(e));return false}};
    {let mut s=shared.lock().unwrap();s.loaded=true;s.recording=true;s.processing=false;s.error.clear();s.text.clear();}
    let _=reply.send(Ok(())); true
}
fn worker(rx:mpsc::Receiver<Cmd>, shared:Arc<Mutex<Shared>>, root:PathBuf) { unsafe { let dll=root.join("native/transcribe.dll"); let api=match Api::new(&dll){Ok(a)=>a,Err(e)=>{set_error(&shared,e);return}}; let _=(api.load_backends)(); let model_root=if root.join("models").exists(){root.clone()}else{root.parent().unwrap_or(&root).to_path_buf()}; let model_path=model_root.join("models/nemotron-3.5-asr-streaming-0.6b-Q4_K_M.gguf"); let mut model: *mut Model=std::ptr::null_mut(); let mut session: *mut Session=std::ptr::null_mut(); let mut audio_rx=None; let mut audio_stream=None; loop { match rx.recv(){ Ok(Cmd::Start(reply))=>{ if !model.is_null(){begin_existing(&api,session,&shared,&mut audio_rx,&mut audio_stream,reply);continue} let path=CString::new(model_path.to_string_lossy().as_bytes()).unwrap(); let mut lp=ModelLoad{size:0,backend:0,_pad:0,device:std::ptr::null_mut()}; (api.model_params_init)(&mut lp); lp.backend=BACKEND_VULKAN; let st=(api.load)(path.as_ptr(),&lp,&mut model); if st!=OK {let e=format!("No se pudo cargar el modelo: {st}");set_error(&shared,e.clone());let _=reply.send(Err(e));continue} let mut sp=SessionParams{size:0,threads:0,kv:0,ctx:0};(api.session_params_init)(&mut sp);let st=(api.session_init)(model,&sp,&mut session);if st!=OK{let e=format!("No se pudo crear sesión: {st}");set_error(&shared,e.clone());let _=reply.send(Err(e));continue} let mut rp=RunParams{size:0,task:0,timestamps:0,pnc:0,itn:0,diarize:0,language:std::ptr::null(),target:std::ptr::null(),keep:false,_pad:[0;7],family:std::ptr::null(),spec:-1,_tail:[0;4]};(api.run_params_init)(&mut rp);let lang=CString::new("es-ES").unwrap();rp.language=lang.as_ptr();let mut pe=ParakeetExt{ext:Ext{size:0,kind:0,_pad:0},right:3,_pad:0};(api.parakeet_init)(&mut pe);pe.right=3;rp.family=std::ptr::null();let mut stp=StreamParams{size:0,family:std::ptr::null(),policy:0,stable:0};(api.stream_params_init)(&mut stp);stp.family=&pe.ext;let st=(api.stream_begin)(session,&rp,&stp);if st!=OK{let e=format!("No se pudo iniciar stream: {st}");set_error(&shared,e.clone());let _=reply.send(Err(e));continue}let (atx,arx)=mpsc::channel();audio_rx=Some(arx);audio_stream=match open_audio_stream(atx){Ok(v)=>Some(v),Err(e)=>{set_error(&shared,e.clone());let _=reply.send(Err(e));continue}};{let mut s=shared.lock().unwrap();s.loaded=true;s.recording=true;s.processing=false;s.error.clear();s.text.clear();}let _=reply.send(Ok(()));}
 Ok(Cmd::Stop(reply))=>{if session.is_null(){let _=reply.send(Ok(String::new()));continue}{let mut s=shared.lock().unwrap();s.recording=false;s.processing=true;}drop(audio_stream.take());if let Some(arx)=audio_rx.take(){while let Ok(chunk)=arx.try_recv(){let mut u=Update{size:0,changed:false,final_:false,revision:0,received:0,committed:0,buffered:0,committed_changed:false,tentative_changed:false,_pad:[0;5]};(api.update_init)(&mut u);let _=(api.feed)(session,chunk.as_ptr(),chunk.len() as i32,&mut u);}}let mut u=Update{size:0,changed:false,final_:false,revision:0,received:0,committed:0,buffered:0,committed_changed:false,tentative_changed:false,_pad:[0;5]};(api.update_init)(&mut u);let st=(api.finalize)(session,&mut u);let text=model_text(&api,session);{let mut s=shared.lock().unwrap();s.processing=false;s.text=text.clone();}let _=reply.send(if st==OK{Ok(text)}else{Err(format!("Finalización: {st}"))});}
 Ok(Cmd::Shutdown)=>{drop(audio_stream.take());if !session.is_null(){(api.session_free)(session);session=std::ptr::null_mut()}if !model.is_null(){(api.model_free)(model);model=std::ptr::null_mut()}break},Err(_)=>break } } } }

fn reply(mut stream:TcpStream, body:String, code:&str){let msg=format!("HTTP/1.1 {code}\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",body.as_bytes().len(),body);let _=stream.write_all(msg.as_bytes());}
fn handle(mut stream:TcpStream, tx:&mpsc::Sender<Cmd>, shared:&Arc<Mutex<Shared>>){let mut b=[0;2048];let n=stream.read(&mut b).unwrap_or(0);let req=String::from_utf8_lossy(&b[..n]);let path=req.split_whitespace().nth(1).unwrap_or("/");match path{"/status"=>reply(stream,status_json(shared),"200 OK"),"/start"=>{let(rtx,rrx)=mpsc::channel();let _=tx.send(Cmd::Start(rtx));match rrx.recv().unwrap_or(Err("motor detenido".into())){Ok(_)=>reply(stream,"OK".into(),"200 OK"),Err(e)=>reply(stream,e,"500 Internal Server Error")}},"/stop"=>{let(rtx,rrx)=mpsc::channel();let _=tx.send(Cmd::Stop(rtx));match rrx.recv().unwrap_or(Ok(String::new())){Ok(t)=>reply(stream,t,"200 OK"),Err(e)=>reply(stream,e,"500 Internal Server Error")}},"/shutdown"=>{let _=tx.send(Cmd::Shutdown);reply(stream,"OK".into(),"200 OK");thread::spawn(||{thread::sleep(std::time::Duration::from_millis(150));std::process::exit(0);});},_=>reply(stream,"Not found".into(),"404 Not Found")}}
fn main(){let root=std::env::current_exe().unwrap().parent().unwrap().to_path_buf();let shared=Arc::new(Mutex::new(Shared::default()));let(tx,rx)=mpsc::channel();let wshared=shared.clone();thread::spawn(move||{ let result=std::panic::catch_unwind(std::panic::AssertUnwindSafe(||worker(rx,wshared.clone(),root))); if result.is_err(){set_error(&wshared,"El worker nativo terminó inesperadamente".into());} });let listener=TcpListener::bind("127.0.0.1:17841").unwrap();for s in listener.incoming().flatten(){let t=tx.clone();let sh=shared.clone();thread::spawn(move||handle(s,&t,&sh));}}







